# Generated by Django 6.0.3 on 2026-07-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('groceries', 'Groceries'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('fuel', 'Fuel'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('subscriptions', 'Subscriptions'), ('savings', 'Savings'), ('other', 'Other')], max_length=20),
        ),
    ]
